### ISSUE TITLE
username is required error

### ISSUE THREAD

**Issue by catchwayrk** [ianramzy/decentralized-video-chat#59]
RKMadugulas-MBP:decentralized-video-chat yesbro$ sudo npm start

> video-chat2@1.0.0 start /Volumes/Projects/ionic/Catchway Projects/dvc/decentralized-video-chat
> node server.js

/Volumes/Projects/ionic/Catchway Projects/dvc/decentralized-video-chat/node_modules/twilio/lib/rest/Twilio.js:145
    throw new Error('username is required');
    ^

Error: username is required
    at new Twilio (/Volumes/Projects/ionic/Catchway Projects/dvc/decentralized-video-chat/node_modules/twilio/lib/rest/Twilio.js:145:11)
    at initializer (/Volumes/Projects/ionic/Catchway Projects/dvc/decentralized-video-chat/node_modules/twilio/lib/index.js:9:10)
    at Object.<anonymous> (/Volumes/Projects/ionic/Catchway Projects/dvc/decentralized-video-chat/server.js:8:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-chat2@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the video-chat2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yesbro/.npm/_logs/2020-06-30T13_26_26_606Z-debug.log

**Comment by ianramzy** [comment]
You need to make sure you properly configure your .env file as specified in the readME with your twillio account credentials. 

1. Rename .env.template to .env
2. Sign up for free twilio account https://www.twilio.com/login
3. Get your Account SID and Auth Token from the Twillio console
4. Fill in your credentials in the .env file
